### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Rikshy** [kenijey/harshenuniverse#134]
https://paste.dimdev.org/ebejadonim.mccrash

ModVersion: 0.15.2
Forge: 14.23.4.2707

Other installed mods:
https://pastebin.com/ADfSHau4

**Comment by kenijey** [comment]
can you provide the installed mods list with the same website you provided crash report please. i can't join pastebin, it's blocked by my internet provider

**Comment by kenijey** [comment]
ok nevermind i got them

**Comment by Rikshy** [comment]
[export-1.0.zip](https://github.com/kenijey/harshenuniverse/files/2151585/export-1.0.zip)

i guess this would be easier :)

without your mod the pack starts up.

**Comment by Rikshy** [comment]
welp :D

**Comment by kenijey** [comment]
i think it crashes with astral sorcery. can you try it? with only astral sorcery, baubles and harshen universe, then see if it crashes please.

**Comment by kenijey** [comment]
i have 1 gb of internet for next 9 days so i dont want to consume it before then :)

**Comment by Rikshy** [comment]
give me a second :)

**Comment by Rikshy** [comment]
Nope, starts up perfectly with AS and HU.


i Added The Erebus after that, and now it crashes.

Now thats wierd...

AS + HU = no crash
Erebus + HU = no crash
AS + Erebus = no crash
AS + Erebus + HU = crash

**Comment by kenijey** [comment]
hmms... i think it's the new dimension(pontus) and the sky rendering incompatibility. SO, the Erebus or Astral Sorcery must add config to disable their sky rendering or dimension tweaking patchs for specific Dimensions(ID). I mean a blacklist for dimension ID. It would be simple for them, especially Astral Sorcery, could easily check the dimension id in their code...

So please report to their side. Harshen Universe currently adds 1 dimension that is Pontus World, and it's dimension ID is I:pontus_dimension=**5**(from config) by default, it's even configurable at my side...

**Comment by kenijey** [comment]
I just noticed that The Erebus mod adds dimension(s). So i may have a solution, can you try changing the Pontus World dimension ID in Harshen Universe configs? Change it to a different number, then try if it will crash.

**Comment by Rikshy** [comment]
Yes, Erebus is a dimension mod! :)
(it's id is 66 by default ->     I:"Dimension ID of The Erebus"=66 )

i changed to id of pontus to 50 - still crash :(

the sky renderer of AS is by default whitelisted to overworld

`
    # Whitelist of dimension ID's that will have special sky rendering [default: [0]]
    S:skySupportedDimensions <
        0
     >`

**Comment by kenijey** [comment]
it's really weird. give me a second

**Comment by Rikshy** [comment]
take your time :)

thanks for your hard work and quick reponse tho, much appriciated!

**Comment by Rikshy** [comment]
btw: are you sure it's sth with sky rendering? i have other dimension mods like Aether II or Aether Legacy and it works just fine without tweaks

**Comment by kenijey** [comment]
thanks. you're working hard too :)

can you try it with this version? see if it crashes. it's without the Pontus World.

[new.zip](https://github.com/kenijey/harshenuniverse/files/2151611/new.zip)

**Comment by Rikshy** [comment]
still crashes. (same crash)

http://pasted.co/fa4544aa (maybe this site is better for you :D)

**Comment by Rikshy** [comment]
If you still need to have someone test, just ask :)

**Comment by kenijey** [comment]
yeah, thank you. at the moment i'm busy with current amazing crashes that blows my mind. :D i hope i can fix all. some of them are extreme brainkilling

**Comment by Rikshy** [comment]
don't die on me mate :D

**Comment by kenijey** [comment]
i'm doing my best :D

**Comment by Rikshy** [comment]
do you need further testing with the new version?

**Comment by kenijey** [comment]
i will release a new version soon which may effect this crash. please wait for that. thank you

**Comment by kenijey** [comment]
can you try it with HU 0.16.0 ?

**Comment by Rikshy** [comment]
Sorry, i was sleeping when you wrote it, currently i am at work!
will test it in about 5-6 hours. :)

**Comment by kenijey** [comment]
no problem man, take your time. i can wait :)

**Comment by Rikshy** [comment]
Nope, sadly still crashes D:

https://justpaste.it/4n92f

**Comment by kenijey** [comment]
no problem :D will look into it after fixing own bugs and uncompleted important things. for now just uninstall the erebus or astral sorcery xD

**Comment by kenijey** [comment]
hey ah, are you still there? for testing a version if it work or so... i can send the jar here.

**Comment by Rikshy** [comment]
give it to me baby

**Comment by kenijey** [comment]
[thing.zip](https://github.com/kenijey/harshenuniverse/files/2173521/thing.zip)

take it :D

**Comment by Rikshy** [comment]
do you have a discord? would be easier than spamming this issue right? ^^

**Comment by kenijey** [comment]
it's already in the mod page :D 
https://discord.gg/kbYhS4
